/**
 * TypeScript port of pipeline/features.py. The 50 module inputs.
 *
 * This must produce byte-for-byte the same vector as the Python extractor, in
 * the same order. If it drifts, every score in the product is wrong in a way
 * nothing will surface: no crash, no error, just numbers that no longer mean
 * what the model was trained on. `features.test.ts` checks a set of headlines
 * against values generated by the Python implementation.
 *
 * Nothing here is a hand-picked word list. Every lexical value is a lookup into
 * published human ratings (Warriner et al. valence/arousal/dominance; Brysbaert
 * et al. concreteness); everything else is a countable property of the text.
 *
 * Coverage is reported as a feature rather than silently ignored: norm
 * dictionaries miss words, and the model should be able to learn to trust
 * sparse-coverage text less.
 */

import normsData from "./norms.json";

interface NormsFile {
  vad: Record<string, [number, number, number]>;
  conc: Record<string, number>;
  stats: Record<string, { mean: number; sd: number }>;
  /** Per-word ratings by demographic segment: [valence, arousal]. */
  demo: Record<string, Record<string, [number, number]>>;
}

const NORMS = normsData as unknown as NormsFile;

/**
 * Function words are excluded from norm averages: they sit near the neutral
 * midpoint and would dilute any real affective signal in the content words.
 * Mirrors STOPWORDS in pipeline/features.py exactly.
 */
const STOPWORDS = new Set(
  `a an the and or but if then than that this these those of to in on at for with
from by as is are was were be been being am do does did doing have has had
having i you he she it we they me him her us them my your his its our their
not no nor so too very can will just don should now`.split(/\s+/),
);

/** Mirrors the Python `[a-z][a-z'-]*` token pattern. */
const WORD_RE = /[a-z][a-z'-]*/g;
const SENT_RE = /[.!?]+/;

export const FEATURE_NAMES: readonly string[] = [
  "arousal_mean_z", "arousal_sd", "arousal_max_z", "arousal_min_z",
  "arousal_range", "arousal_top3_z",
  "valence_mean_z", "valence_sd", "valence_max_z", "valence_min_z",
  "valence_range", "valence_skew", "valence_pos_frac", "valence_neg_frac",
  "dominance_mean_z", "dominance_sd",
  "concrete_mean_z", "concrete_sd", "concrete_max_z", "concrete_min_z",
  "concrete_frac_high", "concrete_frac_low",
  "extremity_mean", "extremity_max", "exclaim_count", "question_count",
  "caps_ratio", "digit_ratio", "has_number", "quote_count",
  "first_word_arousal_z", "last_word_valence_z",
  "n_words", "n_chars", "avg_word_len", "long_word_frac",
  "n_sentences", "avg_sentence_len", "type_token_ratio", "repeat_ratio",
  "vad_coverage", "conc_coverage", "stopword_frac", "punct_density",
  "valence_gender_gap", "arousal_gender_gap",
  "valence_age_gap", "arousal_age_gap",
  "valence_edu_gap", "arousal_edu_gap",
];

export function tokenize(text: string): string[] {
  return text.toLowerCase().match(WORD_RE) ?? [];
}

function z(dim: string, value: number): number {
  const s = NORMS.stats[dim];
  return (value - s.mean) / (s.sd || 1);
}

/** mean, populationSd, min, max, matching Python's `_agg`. */
function agg(v: number[]): [number, number, number, number] {
  if (v.length === 0) return [0, 0, 0, 0];
  if (v.length === 1) return [v[0], 0, v[0], v[0]];
  const mean = v.reduce((a, b) => a + b, 0) / v.length;
  const varSum = v.reduce((a, b) => a + (b - mean) ** 2, 0) / v.length;
  return [mean, Math.sqrt(varSum), Math.min(...v), Math.max(...v)];
}

export function extractFeatures(text: string): Record<string, number> {
  const rawTokens = tokenize(text);
  const content = rawTokens.filter((t) => !STOPWORDS.has(t));
  // Never divide by zero on stopword-only text.
  const lookup = content.length > 0 ? content : rawTokens;

  const val: number[] = [];
  const aro: number[] = [];
  const dom: number[] = [];
  const con: number[] = [];
  const demoAcc: Record<string, [number, number][]> = {
    M: [], F: [], Y: [], O: [], L: [], H: [],
  };

  for (const tok of lookup) {
    const v = NORMS.vad[tok];
    if (v) {
      val.push(v[0]);
      aro.push(v[1]);
      dom.push(v[2]);
      const seg = NORMS.demo[tok];
      if (seg) {
        for (const [k, arr] of Object.entries(seg)) {
          if (demoAcc[k]) demoAcc[k].push(arr);
        }
      }
    }
    const c = NORMS.conc[tok];
    if (c !== undefined) con.push(c);
  }

  /** Mean difference between two segments on one dimension (0 = valence). */
  const demoGap = (a: string, b: string, dim: 0 | 1): number => {
    const xs = demoAcc[a];
    const ys = demoAcc[b];
    if (xs.length === 0 || ys.length === 0) return 0;
    const mx = xs.reduce((s, r) => s + r[dim], 0) / xs.length;
    const my = ys.reduce((s, r) => s + r[dim], 0) / ys.length;
    return mx - my;
  };

  const [vMean, vSd, vMin, vMax] = agg(val);
  const [aMean, aSd, aMin, aMax] = agg(aro);
  const [dMean, dSd] = agg(dom);
  const [cMean, cSd, cMin, cMax] = agg(con);

  // Extremity = distance from the neutral midpoint of the 1-9 scale: strongly
  // polarised wording regardless of direction.
  const extremity = val.map((x) => Math.abs(x - 5));
  const [eMean, , , eMax] = agg(extremity);

  const nWords = rawTokens.length;
  const nChars = text.length;
  const sentences = text.split(SENT_RE).filter((s) => s.trim().length > 0);
  const nSent = Math.max(sentences.length, 1);
  const caps = (text.match(/[A-Z]/g) ?? []).length;
  const digits = (text.match(/[0-9]/g) ?? []).length;
  // The em dash here is DATA, not prose: it is a punctuation mark this feature
  // counts in the user's copy. A project-wide em dash sweep rewrote it to ", "
  // inside the character class, which silently added the space character to
  // the class and roughly quadrupled punct_density on every input. Restored,
  // and the Python parity fixtures are what caught it.
  const punct = (text.match(/[,.;:!?\-—'"()]/g) ?? []).length;
  const uniq = new Set(rawTokens).size;

  const top3 = [...aro].sort((a, b) => b - a).slice(0, 3);
  const top3Mean = top3.length
    ? top3.reduce((a, b) => a + b, 0) / top3.length
    : 0;

  const firstTok = lookup[0];
  const lastTok = lookup[lookup.length - 1];

  return {
    arousal_mean_z: aro.length ? z("arousal", aMean) : 0,
    arousal_sd: aSd,
    arousal_max_z: aro.length ? z("arousal", aMax) : 0,
    arousal_min_z: aro.length ? z("arousal", aMin) : 0,
    arousal_range: aMax - aMin,
    arousal_top3_z: top3.length ? z("arousal", top3Mean) : 0,

    valence_mean_z: val.length ? z("valence", vMean) : 0,
    valence_sd: vSd,
    valence_max_z: val.length ? z("valence", vMax) : 0,
    valence_min_z: val.length ? z("valence", vMin) : 0,
    valence_range: vMax - vMin,
    valence_skew: val.length ? vMean - (vMin + vMax) / 2 : 0,
    valence_pos_frac: val.length
      ? val.filter((x) => x > 6).length / val.length
      : 0,
    valence_neg_frac: val.length
      ? val.filter((x) => x < 4).length / val.length
      : 0,
    dominance_mean_z: dom.length ? z("dominance", dMean) : 0,
    dominance_sd: dSd,

    concrete_mean_z: con.length ? z("concreteness", cMean) : 0,
    concrete_sd: cSd,
    concrete_max_z: con.length ? z("concreteness", cMax) : 0,
    concrete_min_z: con.length ? z("concreteness", cMin) : 0,
    concrete_frac_high: con.length
      ? con.filter((x) => x > 4).length / con.length
      : 0,
    concrete_frac_low: con.length
      ? con.filter((x) => x < 2).length / con.length
      : 0,

    extremity_mean: eMean,
    extremity_max: eMax,
    exclaim_count: (text.match(/!/g) ?? []).length,
    question_count: (text.match(/\?/g) ?? []).length,
    caps_ratio: caps / Math.max(nChars, 1),
    digit_ratio: digits / Math.max(nChars, 1),
    has_number: digits > 0 ? 1 : 0,
    quote_count:
      (text.match(/"/g) ?? []).length + (text.match(/'/g) ?? []).length,
    first_word_arousal_z:
      firstTok && NORMS.vad[firstTok] ? z("arousal", NORMS.vad[firstTok][1]) : 0,
    last_word_valence_z:
      lastTok && NORMS.vad[lastTok] ? z("valence", NORMS.vad[lastTok][0]) : 0,

    n_words: nWords,
    n_chars: nChars,
    avg_word_len: nWords
      ? rawTokens.reduce((a, t) => a + t.length, 0) / nWords
      : 0,
    long_word_frac: nWords
      ? rawTokens.filter((t) => t.length >= 8).length / nWords
      : 0,
    n_sentences: nSent,
    avg_sentence_len: nWords / nSent,
    type_token_ratio: uniq / Math.max(nWords, 1),
    repeat_ratio: 1 - uniq / Math.max(nWords, 1),
    vad_coverage: val.length / Math.max(lookup.length, 1),
    conc_coverage: con.length / Math.max(lookup.length, 1),
    stopword_frac: (nWords - content.length) / Math.max(nWords, 1),
    punct_density: punct / Math.max(nChars, 1),

    // Demographic gap features.
    //
    // These are mostly rating noise (see pipeline/audience_analysis.py), but the
    // model was TRAINED with them, so they must be reproduced exactly here.
    // Sending zeros would be a silent training/serving mismatch. Audience
    // CONDITIONING is a separate concern, handled in lib/segments.ts.
    valence_gender_gap: demoGap("M", "F", 0),
    arousal_gender_gap: demoGap("M", "F", 1),
    valence_age_gap: demoGap("Y", "O", 0),
    arousal_age_gap: demoGap("Y", "O", 1),
    valence_edu_gap: demoGap("L", "H", 0),
    arousal_edu_gap: demoGap("L", "H", 1),
  };
}

/** Feature vector in the exact order the model expects. */
export function extractVector(text: string): number[] {
  const f = extractFeatures(text);
  return FEATURE_NAMES.map((n) => f[n]);
}

/** Share of content words found in the norm dictionaries. Drives a UI warning. */
export function normCoverage(text: string): number {
  const f = extractFeatures(text);
  return f.vad_coverage;
}
