/**
 * TypeScript port of the constrained six-module model.
 *
 * The diagnostic layer runs in-process so a self-hosted deployment needs no ML
 * service. This is a hand port of `model/architecture.py`, and the risk with any
 * hand port is silent numerical divergence. The UI would happily render subtly
 * wrong numbers forever. `module.test.ts` therefore checks this implementation
 * against fixtures generated by PyTorch to 1e-4.
 *
 * The constrained values (C1–C5) are read from the exported JSON in their
 * POST-constraint form. This file must never reapply softplus: the signs are
 * already guaranteed by the exporter, and re-deriving them is exactly how a port
 * flips a sign and inverts a documented effect.
 */

import weights from "./module_model.json";

export type ModuleId =
  | "salience" | "affect" | "valuation" | "encoding" | "approach" | "control";

export interface ModuleScores {
  salience: number;
  affect: number;
  valuation: number;
  encoding: number;
  approach: number;
  control: number;
}

export interface InferenceResult {
  /** Ranking score. Higher is predicted better. Comparable only within a set. */
  score: number;
  /** Post-modulation activations, what the UI displays. */
  modules: ModuleScores;
  /** Pre-modulation activations, before cross-module gating. */
  modulesRaw: ModuleScores;
}

interface ModuleWeights {
  signed: boolean;
  w1: number[][];
  b1: number[];
  ln_gamma: number[];
  ln_beta: number[];
  ln_eps: number;
  w2: number[][];
  b2: number[];
}

interface ModelFile {
  format_version: number;
  n_features: number;
  feature_names: string[];
  scaler: { mean: number[]; sd: number[] };
  module_order: ModuleId[];
  modules: Record<ModuleId, ModuleWeights>;
  constrained: {
    arousal_to_encoding: number;
    arousal_quad: number;
    arousal_lin: number;
    fluency_w: number;
    load_w: number;
    salience_gate_w: number;
    salience_gate_b: number;
    free_w: number[][];
    free_b: number[];
    bias: number[];
  };
  audience: {
    embedding: number[][];
    gain_w: number[][];
    gain_b: number[];
  };
}

const MODEL = weights as unknown as ModelFile;

// ---------------------------------------------------------------- math

/**
 * Abramowitz & Stegun 7.1.26 error function, max error ~1.5e-7, comfortably
 * inside the 1e-4 parity tolerance. Needed because PyTorch's default GELU is
 * the exact erf form, not the tanh approximation.
 */
function erf(x: number): number {
  const sign = x < 0 ? -1 : 1;
  const ax = Math.abs(x);
  const t = 1 / (1 + 0.3275911 * ax);
  const y =
    1 -
    ((((1.061405429 * t - 1.453152027) * t + 1.421413741) * t - 0.284496736) * t +
      0.254829592) *
      t *
      Math.exp(-ax * ax);
  return sign * y;
}

function gelu(x: number): number {
  return x * 0.5 * (1 + erf(x / Math.SQRT2));
}

function sigmoid(x: number): number {
  // Branch to avoid overflow of exp() for large negative x.
  return x >= 0 ? 1 / (1 + Math.exp(-x)) : Math.exp(x) / (1 + Math.exp(x));
}

/** y = W x + b, with W stored row-major as [out][in] to match PyTorch. */
function linear(x: number[], w: number[][], b: number[]): number[] {
  const out = new Array<number>(w.length);
  for (let o = 0; o < w.length; o++) {
    const row = w[o];
    let sum = b[o];
    for (let i = 0; i < row.length; i++) sum += row[i] * x[i];
    out[o] = sum;
  }
  return out;
}

/** LayerNorm with BIASED variance, matching torch.nn.LayerNorm. */
function layerNorm(
  x: number[],
  gamma: number[],
  beta: number[],
  eps: number,
): number[] {
  const n = x.length;
  let mean = 0;
  for (let i = 0; i < n; i++) mean += x[i];
  mean /= n;
  let varSum = 0;
  for (let i = 0; i < n; i++) {
    const d = x[i] - mean;
    varSum += d * d;
  }
  const inv = 1 / Math.sqrt(varSum / n + eps);
  const out = new Array<number>(n);
  for (let i = 0; i < n; i++) out[i] = (x[i] - mean) * inv * gamma[i] + beta[i];
  return out;
}

// ---------------------------------------------------------------- model

/** Standardise raw features with the scaler fitted on training data. */
export function standardise(raw: number[]): number[] {
  const { mean, sd } = MODEL.scaler;
  if (raw.length !== mean.length) {
    throw new Error(
      `Expected ${mean.length} features, received ${raw.length}. ` +
        "Feature extraction and model weights are out of sync.",
    );
  }
  const out = new Array<number>(raw.length);
  for (let i = 0; i < raw.length; i++) out[i] = (raw[i] - mean[i]) / sd[i];
  return out;
}

function runModule(x: number[], m: ModuleWeights): number {
  // Dropout is identity at inference, deliberately absent, not forgotten.
  const h = layerNorm(linear(x, m.w1, m.b1), m.ln_gamma, m.ln_beta, m.ln_eps);
  for (let i = 0; i < h.length; i++) h[i] = gelu(h[i]);
  const z = linear(h, m.w2, m.b2)[0];
  return m.signed ? Math.tanh(z) : sigmoid(z);
}

/**
 * Forward pass.
 *
 * @param standardised Features already passed through `standardise`.
 * @param audienceIndex Optional demographic segment index.
 */
export function infer(
  standardised: number[],
  audienceIndex?: number,
): InferenceResult {
  const acts: Record<string, number> = {};
  for (const id of MODEL.module_order) {
    acts[id] = runModule(standardised, MODEL.modules[id]);
  }

  // Audience conditioning: multiplicative gain centred on 1, so an unknown
  // audience is a no-op rather than a distortion.
  if (audienceIndex !== undefined) {
    const emb = MODEL.audience.embedding[audienceIndex];
    if (!emb) throw new Error(`Unknown audience index: ${audienceIndex}`);
    const gains = linear(emb, MODEL.audience.gain_w, MODEL.audience.gain_b);
    MODEL.module_order.forEach((id, i) => {
      acts[id] *= 1 + Math.tanh(gains[i]);
    });
  }

  const raw = { ...acts } as unknown as ModuleScores;
  const c = MODEL.constrained;

  // C3, attention gates valuation.
  const gate = sigmoid(c.salience_gate_w * acts.salience + c.salience_gate_b);
  acts.valuation *= gate;

  // C2, arousal enhances memory encoding.
  acts.encoding *= 1 + c.arousal_to_encoding * acts.affect;

  // C1, inverted-U in arousal. arousal_quad is negative by construction.
  const a = acts.affect;
  const arousalTerm = c.arousal_quad * a * a + c.arousal_lin * a;

  // C4 / C5, fluency helps (+), cognitive load hurts (−).
  const fluency = acts.control;
  const controlTerm = c.fluency_w * fluency + c.load_w * (1 - fluency);

  const free = linear(
    [acts.salience, acts.valuation, acts.encoding],
    c.free_w,
    c.free_b,
  )[0];

  return {
    score: arousalTerm + controlTerm + free + c.bias[0],
    modules: acts as unknown as ModuleScores,
    modulesRaw: raw,
  };
}

/**
 * Constraint C2's gate: encoding is multiplied by (1 + this * affect).
 * Exposed so display code can compute the true range of the encoding score
 * instead of assuming 0-1 and silently clipping it.
 */
export function arousalToEncoding(): number {
  return MODEL.constrained.arousal_to_encoding;
}

/** Arousal level the model considers optimal. The vertex of the inverted-U. */
export function arousalOptimum(): number {
  const c = MODEL.constrained;
  return Math.min(1, Math.max(0, -c.arousal_lin / (2 * c.arousal_quad)));
}

export const FEATURE_NAMES: readonly string[] = MODEL.feature_names;
export const MODEL_PROVENANCE = (MODEL as unknown as {
  provenance: Record<string, unknown>;
}).provenance;
